# Generated by Django 2.2.6 on 2019-10-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servis',
            options={'verbose_name_plural': 'Servis Kayıtları'},
        ),
    ]
